spring.application.name=demo

spring.datasource.url=jdbc:postgresql://dpg-d6kgq37kijhs73fifub0-a:5432/tt_n0k6
spring.datasource.username=tt_n0k6_user
spring.datasource.password=7iB3hQwVri1II2un9b7s9MovI9a6l3p3
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8080}
